// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID             int32
	TelegramChatID int32
	Context        []byte
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
}

type Job struct {
	ID             int32
	TelegramChatID int32
	IsRecurring    bool
	RiverJobID     pgtype.Int8
	Message        string
	Schedule       string
	Name           string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
}
